resources:
  - name: execTemplatesGit
    type: GitRepo
    configuration:
      path: vijayreddy1991/tryout-extension
      gitProvider: vijay
      branches:
        include: ^{{gitBranch}}$
      files:
        include: \bexecTemplates\/.+\b

  - name: testResource
    type: testing/SampleResource
    configuration:
      foo: Hello


pipelines:
 - name: sleep_pipeline_extension
   steps:
      - name: S_Bash_0023
        type: shippable/HealthCheck
        configuration:
           healthCheckUrl: https://www.google.com/
           notifyOnSuccess: true
           notifyOnFailure: true
           stuff:
              - "hi"
              - "hello"
           integrations:
            - name: Slack
           inputResources:
            - name: execTemplatesGit
